### ISSUE TITLE
TypeError: null is not an object (evaluating 'n.title')

### ISSUE THREAD

**Issue by cesargdm** [LogRocket/logrocket#19]
I've got a Sentry error reporting a issue in 

```
TypeError: null is not an object (evaluating 'n.title')
  at wrapped(../node_modules/logrocket/dist/build.umd.js:641:23)
  at r(../../src/helpers.ts:87:17)
```

**Comment by tonydehnke** [comment]
I get these quite often too - how were you able to determine it as a LogRocket issue?  It seems they don't monitor the issues here often.  Did you submit it as a bug to them directly?

**Comment by markatlish** [comment]
Also just received this. Stack trace is from logrocket/dist/build.umd

**Comment by markatlish** [comment]
Adding @rlucioni if this is a quick fix in LogRocket / for how to report bugs
